version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
    open-pull-requests-limit: 10
    labels:
      - "Dependencies"
    versioning-strategy: "increase-if-necessary"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "CI"
    groups:
      doctrine:
        patterns:
          - "doctrine/*"
